---
- name: Install apt packages
  hosts: k8stemplate
  become: true
  tasks:
    - name: Disable Swap file in /etc/fstab
      ansible.builtin.shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    - name: Set overlay network kernel module to load
      ansible.builtin.shell: echo "overlay">/etc/modules-load.d/containerd.conf
    - name: Set network bridging kernel module to load
      ansible.builtin.shell: echo "br_netfilter">>/etc/modules-load.d/containerd.conf
    - name: Set network bridge ipV6
      ansible.builtin.shell: echo "net.bridge.bridge-nf-call-ip6tables = 1">/etc/sysctl.d/kubernetes.conf
    - name: Set network bridge ipV4
      ansible.builtin.shell: echo "net.bridge.bridge-nf-call-iptables = 1">>/etc/sysctl.d/kubernetes.conf
    - name: Set network forwading
      ansible.builtin.shell: echo "net.ipv4.ip_forward = 1">>/etc/sysctl.d/kubernetes.conf
    - name: Get Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Get Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    - name: Add Kubernetes Repo
      ansible.builtin.apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
    - name: Install Kubernetes packages
      ansible.builtin.apt:
        update_cache: true
        name: 
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - containerd
          - kubelet
          - kubeadm
          - kubectl
        state: present
