---
- name: Install Proxmox apt packages to build cloud-images with debug output
  hosts: proxmox
  become: true
  tasks:
    - name: Install multiple packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - libguestfs-tools
        state: present
      register: apt_output

    - name: Print debug output
      debug:
        var: apt_output
